### ISSUE TITLE
Lang story bugger i map-view

### ISSUE THREAD

**Issue by DPaaske** [andersravn/citystoriesapp#10]
En "for-lang" entry bugger når man prøver at se den i map-viewet. Den åbner momentant men lukker øjeblikkeligt og ens zoom på kortet hopper opad.

**Comment by andersravn** [comment]
Når du siger "prøver at se den i map-viewet" mener du så at du trykker "Vis på kort"?

**Comment by DPaaske** [comment]
Det prøvede jeg faktisk ikke lige. Men den gør det når man  trykker på markeren på kortet.

**Comment by andersravn** [comment]
Jeg kan ikke reproducere dette på HTC One'en. Jeg har oprettet en meget lang entry, og den åbner fint i map viewet, hvor den er truncatet.

**Comment by andersravn** [comment]
Men jeg har så problemet på min iPhone...

**Comment by andersravn** [comment]
Det var igen noget vi manglede i myStories loopet i updateMarkers. Vi manglede truncate filteret. Så det virkede fint når man ikke var logget ind, men når man var logget ind, og entries blev renderet som mystories, så blev de ikke truncatet.
